/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiPushCronRouteImport } from './routes/api/push/cron'
import { Route as ApiPushZoneCronRouteImport } from './routes/api/push/zone-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushCronRoute = ApiPushCronRouteImport.update({
  id: '/api/push/cron',
  path: '/api/push/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushZoneCronRoute = ApiPushZoneCronRouteImport.update({
  id: '/api/push/zone-cron',
  path: '/api/push/zone-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/push/cron': typeof ApiPushCronRoute
  '/api/push/zone-cron': typeof ApiPushZoneCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/push/cron': typeof ApiPushCronRoute
  '/api/push/zone-cron': typeof ApiPushZoneCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/push/cron': typeof ApiPushCronRoute
  '/api/push/zone-cron': typeof ApiPushZoneCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/signup' | '/api/push/cron' | '/api/push/zone-cron'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/api/push/cron' | '/api/push/zone-cron'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/api/push/cron'
    | '/api/push/zone-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPushCronRoute: typeof ApiPushCronRoute
  ApiPushZoneCronRoute: typeof ApiPushZoneCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/cron': {
      id: '/api/push/cron'
      path: '/api/push/cron'
      fullPath: '/api/push/cron'
      preLoaderRoute: typeof ApiPushCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/zone-cron': {
      id: '/api/push/zone-cron'
      path: '/api/push/zone-cron'
      fullPath: '/api/push/zone-cron'
      preLoaderRoute: typeof ApiPushZoneCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPushCronRoute: ApiPushCronRoute,
  ApiPushZoneCronRoute: ApiPushZoneCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
